### ISSUE TITLE
which is the default projection ?

### ISSUE THREAD

**Issue by juliettelavoie** [Ouranosinc/figanos#278]
### Setup Information

- figanos version:
- Python version:
- Operating System:

### Description

In the docs, it says that Lambert Conformal is the default (this is also what I thought it was), but the actual default is PlateCarree.

@sarahclaude which one do we want ? I am leaning for Lambert.

### Contribution

- [X] I would be willing/able to open a Pull Request to address this bug.

**Comment by sarahclaude** [comment]
PlateCarree will have to be the default projection in hvplot since LambertComformal does not work (unless someone wants to create the code necessary for it work similar to this: https://discourse.holoviz.org/t/cant-show-hover-as-lon-lat-degree-with-projection/3834/5 , since I wasn't successful when I tried)  .
Apart from that, I don't mind either Lambert or PlateCarree

**Comment by juliettelavoie** [comment]
ok ! My preference would be to have lambert conformal as default  for matplotlib even if that's not possible in interactive

**Comment by Zeitsperre** [comment]
I don't often get the chance to these days, but I want to put on my geographer hat and jump in here.

I'm curious what kind of data we are typically supporting here: Are we able to support dynamic projections based on spatial extent?

[Lambert Conformal Conic](https://www150.statcan.gc.ca/n1/pub/92-195-x/2011001/other-autre/mapproj-projcarte/m-c-eng.htm) has been the standard projection used for Canada since the 1970s. If we just want a standard global projection, the Robinson Projection does the job.

If we really want something fun, the [AuthaGraph Projection](https://en.wikipedia.org/wiki/AuthaGraph_projection) is great, though I doubt it's supported by most libraries...

**Comment by juliettelavoie** [comment]
I think most map produce at Ouranos are Quebec and Canada. Hence, the choice of Lambert as a default.
I guess it could be possible have different defaults for different spatial extents, you are welcome to make a PR ! 

I don't see AuthaGraph in cartopy, which is what we are using...
